language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    - extra-android-support

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  
jdk:
  - oraclejdk8

branches:
only:
  - develop
  - master

env:
  global:
    - ADB_INSTALL_TIMEOUT=8

notifications:
  email: false

sudo: false

script:
  - chmod +x ./gradlew

cache:
  directories:
    - $HOME/.gradle
